import type { Metadata } from "next";
import { Toaster } from "@/components/ui/toaster"
import "./globals.css";
import { Roboto } from 'next/font/google'
import { SessionProvider } from "next-auth/react";
import CartSidebar from "@/components/shared/CartSidebar";
import { auth } from "@/auth";
import SyncCart from "@/components/shared/SyncCart";
import { getAuthenticatedUserCart } from "@/actions/cart.actions";
import OrderDetailsSidebar from "@/components/modals/OrderDetailsSidebar";


import StoreProvider from "@/components/shared/StoreProvider";

const roboto = Roboto({
  weight: ["400","500", "700", "900"],
  subsets: ["latin"],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({

  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
 
  const session = await auth()
  const result = session ? await getAuthenticatedUserCart({userId:session?.user.id}) : null;
  
  return (
    <html lang="en">
     
     
      <body
        className={`${roboto.className}`}
      >
         <StoreProvider>
         <SessionProvider session={session}>
       <CartSidebar data={result?.data || null}  />
       <OrderDetailsSidebar   />
       <SyncCart />
        {children}
        <Toaster />
        </SessionProvider>
        </StoreProvider>
      </body>
     
      
    </html>
  );
}
