import type { Metadata } from "next";

import "./globals.css";
import { Roboto } from 'next/font/google'

import CartSidebar from "@/components/shared/CartSidebar";

const roboto = Roboto({
  weight: ["400","500", "700", "900"],
  subsets: ["latin"],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      
     
      <body
        className={`${roboto.className}`}
      >
       <CartSidebar />
        {children}
       
      </body>
     
     
    </html>
  );
}
